### PR TITLE
Clean up the temporary branches for PR with forked branches

### PR DESCRIPTION
**Pull request by ktsai7**

### CODE REVIEW

**Comment by tuxfan** [comment]
@junghans :could you, please ,review this?

**Comment by ktsai7** [comment]
But don't we push to gh-pages?

**Comment by junghans** [comment]
You are right, but you will need to do your stuff after the keys got decrypted in the after_sucess block.

**Comment by ktsai7** [comment]
@junghans I put the code in the after success block where the documentation used to be.

**Pull request merged**
