### PR TITLE
Initial HPX implementation

### PR DESCRIPTION
**Pull request by hkaiser**
- fixing warnings reported by MSVC
- Fix indentation
- Resolving rebase conflicts
- Making sure initialize() returns only after all activity has ceased
- Executing tasks using hpx::async
- started to implement tasks_and_drivers example
- Adapting to latest changes, directly execute tlt_driver before starting HPX
- Suppressing warnings
- Initialize HPX in context policy, run driver() as HPX thread
- simple_drivers is functional
- Add missing functions to uint128
- work around MSVC problems
- Duplicated serial runtime model to HPX
- added build system support for HPX
- flyby: various fixes for MSVC: added __uint128_t, exported symbols, minor workarounds

### CODE REVIEW

**Comment by junghans** [comment]
Some of the Travis test are broken on master, too, but not all!

Which version of hpx is needed here? So that we can add it to flecsi-third-party.

**Comment by hkaiser** [comment]
> Some of the Travis test are broken on master, too, but not all!

I would have expected this ;-)

> Which version of hpx is needed here? So that we can add it to flecsi-third-party.

I'm working against top of master and have not tried using any older versions. We probably should build against master for the time being (until things have stabilized a bit).

**Comment by hkaiser** [comment]
> > Some of the Travis test are broken on master, too, but not all!
>
> I would have expected this ;-)

I meant: I would have expected for this patch to break things. I have not run all the tests locally. I will work on fixing the problems introduced by this patch.

**Comment by hkaiser** [comment]
I think I fixed the problems I introduced, The remaining problems are unrelated (AFAICS) to the proposed changes.

**Comment by ipdemes** [comment]
Great! Thank you, Hartmut!

**Comment by hkaiser** [comment]
@junghans Thanks for taking care of the finer points of integration with the build infrastructure!

**Comment by junghans** [comment]
It seems this PR makes the MPI backend not compile anymore:
https://travis-ci.org/laristra/flecsi/builds/326041618
even though the last merged master version (552122b89a3c1085c979d1e300b4cd30b06a0f74), builds fine:
https://travis-ci.org/laristra/flecsi/builds/325941428

**Comment by hkaiser** [comment]
@junghans ok, I'll investigate this. I'm not aware of consciously having changed anything related to this, but rebasing of older changes on top of the newer master branch could have messed up things...

**Comment by junghans** [comment]
Ok the sonarqube Jobs fails as this isn’t internal pull request (And I will fix that).

But the hpx backend still has some compile errors, too!

**Comment by junghans** [comment]
Does the hpx backend need `ENABLE_COLORING=ON` ?

**Comment by hkaiser** [comment]
> Does the hpx backend need ENABLE_COLORING=ON ?

Not at this point. It may be needed later on.

**Comment by hkaiser** [comment]
@junghans I think I have accidentally overwritten (through a force-push) one or more of your recent commits. Could you reapply those, please?

**Comment by junghans** [comment]
Now it is broken with `ENABLE_COLORING=ON`, I guess..

**Comment by hkaiser** [comment]
> Now it is broken with ENABLE_COLORING=ON, I guess..

Working on it...

**Comment by ipdemes** [comment]
@hkaiser : i have just got back from my vacations and wondering if you need any help?

**Comment by hkaiser** [comment]
\o/  Thanks a lot!

**Pull request merged**
