### PR TITLE
Additional utils/ unit tests and tweaks.

### PR DESCRIPTION
**Pull request by staleyLANL**
More utils/ unit tests. Re-used branch name.
Unit tests were always done both before and after any .h file changes. :-)

### CODE REVIEW

**Comment by charest** [comment]
You should get in the habit of not putting a filename after the doxygen command `\file`, because  if you make a mistake, or the file is moved, doxygen will not pick it up anymore.  Using 

    //! \file

Instead of 

    //! \file debruijn.h

is safer i think.

**Comment by staleyLANL** [comment]
@charest: noted; I'll change those. I'd seen the file name after //! \file in some places, thought that that might be preferred, and was making the others consistent with those cases.

**Comment by charest** [comment]
I think this is something we've learned recently, and haven't fixed everywhere yet

**Comment by staleyLANL** [comment]
I can fix it everywhere, then, as I work through the code.

**Comment by staleyLANL** [comment]
By the way, I noticed that debruijn32_t::index(0) gives 0, which isn't really the correct result, given the function's description. uint32_t(0) doesn't have a 1 bit anywhere - including in the 0 position. A better result might be, say, uint32_t(-1), to be interpreted as "no 1 bit in any position." I traced the function's use for a little ways, but didn't determine if anyone would ever send an argument of 0, or depend on the result of such a call being 0, or have any problems if the result were uint32_t(-1) instead. It may not be important, but let me know if anyone has any comments about that.

**Pull request closed without merging**
