### PR TITLE
Feature/staley/utils id more

### PR DESCRIPTION
**Pull request by staleyLANL**
More cleanup to the utils id_ class.

### CODE REVIEW

**Comment by ipdemes** [comment]
@staleyLANL : did you check if FleCSALE-MM works with your changes?

**Comment by staleyLANL** [comment]
@ipdemes No, not yet. My flecsale-mm seems to have been broken lately; something about the python library. I don't know what changed in order to cause that.

**Comment by staleyLANL** [comment]
@ipdemes All tests pass for flecsale-mm with this branch on Darwin with MPI.

**Comment by ipdemes** [comment]
@staleyLANL : could you, please , also test with legion and update with the most recent master

**Comment by staleyLANL** [comment]
@ipdemes Yes, I can do that; just remember that flecsale-mm's master branch with legion on Darwin fails those three tests. I can verify that the utils::id changes don't cause it to fail additional tests.

**Comment by staleyLANL** [comment]
@ipdemes I ran the flecsale-mm tests again on Darwin this morning. With mpi, all tests pass both with flecsi master, and flecsi with this branch. With legion, those same three tests fail both with flecsi master, and with my branch. Whatever the problem is with legion, I believe that my utils-id-more branch is fine, because results are consistent with those of master.

**Pull request merged**
