### PR TITLE
Barrier per field

### PR DESCRIPTION
**Pull request by ipdemes**

### CODE REVIEW

**Comment by junghans** [comment]
@ipdemes: Can you fix these conflicts?

**Comment by ipdemes** [comment]
@junghans, sure, I'll do this.

**Comment by jpietarilagraham** [comment]
What conflicts?  I'm merging barrier_per_field and master manually in a private branch at the moment.  Did you try to do an automatic merge?

--
Jonathan Graham
Applied Computer Science, CCS-7
(505) 665-2482 / jgraham@lanl.gov
________________________________________

**Comment by jpietarilagraham** [comment]
Please checkout branch for_irina.

I've been working on this merge all morning already.

--
Jonathan Graham
Applied Computer Science, CCS-7
(505) 665-2482 / jgraham@lanl.gov
________________________________________

**Pull request closed without merging**
