### PR TITLE
Tweak ABC mesh_definition_u for master

### PR DESCRIPTION
**Pull request by cmsquared**
Mirror of #553 but for the master branch.

Finishes closing #508

### CODE REVIEW

**Comment by ktsai7** [comment]
For the gitlab-ci, it seems like the pipeline is out-of-date. Could you merge master into this branch to update?

**Comment by ktsai7** [comment]
Also, seems like there is format failure. Please run make format in your build directory.

**Comment by cmsquared** [comment]
@ktsai7 I'm not sure what you mean about needing to be merged with master.  This branch was based on master as of this morning, and diffs only show the differences in this PR.  Am I missing something?

As for clang-format, I manually ran that on our HPC systems, but the newest we have there is 6.0.1 (hence the manual run rather than `make format`).  Hopefully this works...

**Comment by ktsai7** [comment]
Ohh, sorry I didn't realize there was abc_tweaks_mesh and abc_tweaks_mesh_master.
The pipeline for abc_tweaks_mesh seems to be using an older version of gitlab-ci.yml, not abc_tweaks_mesh_master.

As for the formatting, I think it worked.

**Comment by cmsquared** [comment]
I'm open to doing this another way rather than having two PRs to two different branches for basically the same changes.  We need one on the release/0.1 branch because that is where most of our current FY work will be based upon.  But this change also needs to be in master for others.

**Comment by ktsai7** [comment]
Both PRs should be going through soon, so let's just keep going.
As far as the changes and fixes go, I think this way is fine since release branches diverge from master and we cannot guarantee changes for the releases would just work for master as it is...
We just need to pay attention to the names more closely in the future.

**Comment by charest** [comment]
@ipdemes how did this get merged if it broke flecsale?  I thought there were tests to run all pull requests against flecsale?

**Comment by ktsai7** [comment]
Because there was a bug in the way that building flecsale was added to the tests!
I just went in and fixed it.

@charest do you already have a PR fixing this or do you need help fixing this? I won't be able to merge the fix on the ci file before this is fixed anyway.

**Comment by ipdemes** [comment]
@ktsai7 : Karen, do you know if FleCSALE was checked during this PR?

**Comment by cmsquared** [comment]
@ktsai7 #562 should fix this

**Pull request merged**
