### PR TITLE
Enable and make work simple_task test for HPX

### PR DESCRIPTION
**Pull request by hkaiser**
This relies on  https://github.com/laristra/cinch/pull/124, STEllAR-GROUP/hpx#3179, and laristra/cinch#125 to be merged first.

### CODE REVIEW

**Comment by ipdemes** [comment]
@hkaiser : I have updated the hpx submodule and rerun the build. The hpx tests are failing now with the error like below both on travis and my local machine, I think this is unrelated to the hpx itself and you just need to add "domain" member to your "data_client_handle_index_subspace_t" class

In file included from /home/irina/development/flecsi_hpx/flecsi/flecsi/data/data.h:18:0,
                 from /home/irina/development/flecsi_hpx/flecsi/flecsi/execution/test/simple_function.cc:8:
/home/irina/development/flecsi_hpx/flecsi/flecsi/data/client.h: In static member function ‘static flecsi::data_client_handle__<DATA_CLIENT_TYPE, 0ul> flecsi::data::data_client_policy_handler__<flecsi::topology::mesh_topology__<POLICY_TYPE> >::get_client_handle()’:
/home/irina/development/flecsi_hpx/flecsi/flecsi/data/client.h:427:11: error: ‘struct flecsi::data_client_handle_index_subspace_t’ has no member named ‘domain’
       iss.domain = si.domain;
           ^~~~~~
/home/irina/development/flecsi_hpx/flecsi/flecsi/data/client.h:428:11: error: ‘struct flecsi::data_client_handle_index_subspace_t’ has no member named ‘dim’
       iss.dim = si.dim;

**Comment by hkaiser** [comment]
@ipdemes will fix.

**Comment by ipdemes** [comment]
@hkaiser : actually, the reason for the failing build is that there were following changes applied to the cinch: before in cinch I have explicitly disabled tutorial builds for the hpx runtime, when now tutorial build is enable by default for all runtimes, but we have a cmake option to disable it (-DENABLE_FLECSI_TUTORIAL=OFF). FleCSI with hpx runtime will comile and run with no errors when I configure FleCSI with -DENABLE_FLECSI_TUTORIAL=OFF. I am trying to add the logic to the travis builds to disable tutorial build for the hpx runtime for a while (before we get more features implemented for the hpx runtime)

**Comment by hkaiser** [comment]
@ipdemes thanks for investigating. I thought I disabled the tutorial for HPX builds, apparently I didn't :/

**Comment by ipdemes** [comment]
@hkaiser : I believe you just need to cherry-pick following commit to get travis tests pass:
https://github.com/laristra/flecsi/commit/068c23f95aad2d8908376eff72e9b52861d63d36

**Comment by hkaiser** [comment]
@ipdemes nod, I did just now. Actually, I had a similar patch locally on my disk... :/ - thanks!

**Comment by ipdemes** [comment]
@hkaiser : I see, Anyway it seems like disabling tutorials didn't fix the error at this branch  and  you still need to add " domain" and "dim" members to your "data_client_handle_index_subspace_t" class.

**Comment by ipdemes** [comment]
@hkaiser : I have restarted the build today and all tests have passed (https://travis-ci.org/laristra/flecsi/builds/349077203?utm_source=github_status&utm_medium=notification). I guess the future_handle test failed due to some travis build error last time . So I will go ahead and merge the pull request.

**Comment by ipdemes** [comment]
@hkaiser : P.S. sorry it took so long to do this

**Comment by hkaiser** [comment]
@ipdemes Thanks for all your support!

**Pull request merged**
