### PR TITLE
Feature/jloiseau/tree

### PR DESCRIPTION
**Pull request by JulienLoiseau**

### CODE REVIEW

**Comment by JulienLoiseau** [comment]
- Adding directories for each topology for readability 
- Adding tree topology based on FleCSI storage with traversal 
- Adding test for tree and filling cruves

**Comment by ipdemes** [comment]
@tuxfan do we want to merge it here or move to the refactor branch?

**Comment by ipdemes** [comment]
per discussion with @tuxfan this work should be moved to the refactor branch.

**Comment by tuxfan** [comment]
Moving this to feature/refactor

**Pull request closed without merging**
