### PR TITLE
Add simple test of legion serdez capability

### PR DESCRIPTION
**Pull request by cferenba**
Redo of #551 from a branch instead of a fork, to enable gltlab CI...

### CODE REVIEW

**Comment by cferenba** [comment]
It looks like the gitlab tests failed because clang could not be found - @junghans or @ktsai7 , any idea what's happening here?

**Comment by charest** [comment]
I updated clang to version 7 for flecstan, but on ubuntu the executable is acually called clang-7.

I submitted a fix to flecsi-buildenv, then we need to rebuild flecsi-third-party once that patch is merged.

**Comment by ktsai7** [comment]
@charest Is this related to what you said CI might be broken with ubuntu clang last week during tea time?

**Comment by cferenba** [comment]
@tuxfan or @ipdemes can you approve?

**Pull request merged**
