### PR TITLE
simple_function test is still broken

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by ipdemes** [comment]
Ok. It is failing only with OpenMPI. So, what have we decided to do with an OpenMPI builds? Should we just have TRAVIS to build OpenMPI with MPI_THREAD_MULTIPLE support ? I have checked GASNET_udp conduit - it will not work on TRaVIS since it will require 2 cores for some of our tests.

**Comment by junghans** [comment]
Actually, `simple_function` fails on mpich with clang too: https://travis-ci.org/laristra/flecsi/jobs/247342821

**Comment by ipdemes** [comment]
Does clang build use OpenMPI? Because the error message is the same as for the gcc+OpenMPI build.

**Comment by junghans** [comment]
We will fix that later.

**Pull request closed without merging**
