### PR TITLE
Header cleanup

### PR DESCRIPTION
**Pull request by opensdh**
Not even `boost::program_options` can have a *using-directive* at namespace scope in a header.  It's just a bug that they didn't call it `boost::argv`.

### CODE REVIEW

**Comment by staleyLANL** [comment]
I'm curious, why the change from _topology to _topo? The former strikes me as being much more descriptive. Did we just want something shorter? For what it's worth, personally I've always liked a "big endian" naming style; say, all topology types beginning with "topology_" (or "topo_"), so that we know immediately, from the prefix, what sort of animal we're dealing with. But that's just an opinion.

**Comment by staleyLANL** [comment]
Definitely agree about the namespace-scope usings. We should never foist such a thing on everyone who includes the header!

**Comment by opensdh** [comment]
> I'm curious, why the change from _topology to _topo? The former strikes me as being much more descriptive. Did we just want something shorter?

Getting rid of the `_u` prefixes caused collisions between things like `flecsi::topology::global_topology` (the class template) and `flecsi::data::global_topology` (the namespace).  My hope is to get rid of the latter sort entirely (by combining the various class templates named `accessor` in those namespaces), so as a stopgap I adjusted those names.

On the subject of shorter names, sometimes it's good to make especially namespace names shorter (so long as they're still mnemonic) for two reasons:

1. Long name components that get used more than once in a "line" can easily drown the real meaning of the line (_e.g._, `long_namespace_name::good_type_name get_thing(long_namespace_name::argument_type,long_namespace_name::setting_type);`).
1. It lets people realistically qualify their names rather than feeling the need to apply `using` everywhere.  (In Python, for example, I usually advocate "one `.`" naming: `from os import path; path.join(...)`, not `import os.path; os.path.join(...)` or `from os.path import join; join(...)`.)

> For what it's worth, personally I've always liked a "big endian" naming style; say, all topology types beginning with "topology_" (or "topo_"), so that we know immediately, from the prefix, what sort of animal we're dealing with. But that's just an opinion.

I'm not quite sure which names you mean: the things I renamed were not topology _types_.  As for big-endian names in general, we already have that in the form of the namespace names, so we can use (say) `flecsi::topology::global` instead of the current, redundant `flecsi::topology::global_topology_t`.  (That is, we have that big-endian situation if people qualify the names!  Thus the value in making them typeable.)

**Comment by opensdh** [comment]
> Definitely agree about the namespace-scope usings. We should never foist such a thing on everyone who includes the header!

It's worse than that, even, since such directives can affect the interpretation of other header files thereafter `#include`-d&hellip;

**Comment by opensdh** [comment]
The `utils::voided` change reuses (and names) a pattern already being used in `type_traits.hh` that is Clang-compatible.

**Pull request merged**
