### PR TITLE
Fix register_field to match new ragged/sparse implementation

### PR DESCRIPTION
**Pull request by cferenba**
This fixes a bug in the new ragged/sparse implementation discovered by @ipdemes.  There was a field size mismatch that could only be detected by building against a debug version of legion.

I had previously modified the handles, accessors, and mutators for sparse data to include the `size_t` entry number as part of the type; but didn't make the same change to the initial `register_field` call.  This commit fixes that.  As a result, several occurrences of `+ sizeof(size_t)`, particularly in the legion backend, are no longer needed and can be removed.

### CODE REVIEW

**Comment by cferenba** [comment]
@junghans or @ktsai7 : What do the failed codecov/patch results mean?  Unless the CI is doing something really weird, we should be getting at least partial coverage of the changes.

**Comment by junghans** [comment]
It is 0% in diff coverage, so the change is coverage as much as before (9.8% total).

**Comment by cferenba** [comment]
Then why is the build marked as a failure?

**Comment by ipdemes** [comment]
@junghans @ktsai7 Should we disable codecov for now?

**Comment by junghans** [comment]
Because the target diff coverage is 9.8% meaning to constantly increase the coverage. As coverage increase isn't required, just don't worry about it.

**Comment by junghans** [comment]
@ipdemes it isn't required, but just FYI at this point.

**Comment by ipdemes** [comment]
@junghans that is good ;)

**Comment by cferenba** [comment]
pinging @ipdemes or @tuxfan for a review...

**Comment by ipdemes** [comment]
@cferenba : why did you remove "+ sizeof(size_t)" from the sparse case? It doesn't use it anymore?

**Comment by cferenba** [comment]
@ipdemes : The `+ sizeof(size_t)` is done once at field registration time (for sparse data only).  From then on it is included in `field_info.size` and doesn't need to be added again.

**Comment by ipdemes** [comment]
@cferenba  I see. Thank you for the details. I'll approve the pull request now.

**Pull request merged**
