### PR TITLE
fixed mesh_definition interface to return by ref

### PR DESCRIPTION
**Pull request by charest**

### CODE REVIEW

**Comment by cferenba** [comment]
Looks like I didn't get my comment in fast enough...

It's good that you added this functionality, but the way it's organized is very different from the idiom used by the std containers such as map.  So there's potential for confusion.  If there's an opportunity to rework this later, I'd suggest organizing it similarly to map:
- `operator[]` always returns a reference, creating a new entry if necessary;
- `at()` returns a reference only if the entry exists, giving an error otherwise.
Note that there already exists a `contains()` method to test whether an entry is present (again, this is similar to map).

**Comment by charest** [comment]
The sparse_accessor cannot ad an entry if it doesnt exist, because it is not a mutator.  And the way that the current at() function works, returning a pair (basically) is the same as things like std::map::try_emplace works.  Except I created a type for better readability instead of a pair with 'first' and 'second' members.  So there is no way to really match the std library exactly.  Maybe "at" asserts if not found, and operator() doesnt.  But what reference do you return if it does not assert?  Maybe operator() returns a reference, and at returns a constant value only?

I am not tied to the names i chose.  So If you want to rename "at" to something else, or "contains" to "exists" thats ok.

**Comment by cferenba** [comment]
Good points, I wasn't looking closely enough.  Let me think on this some more...

**Comment by cmsquared** [comment]
@charest or @cferenba  are the changes to sparse accessor needed/consistent with release/0.1?  I'm trying to cherry-pick what we need in 0.1 that has been recently merged into master.

**Comment by charest** [comment]
We should just point release/0.1 at master

**Comment by cferenba** [comment]
> @charest or @cferenba are the changes to sparse accessor needed/consistent with release/0.1? I'm trying to cherry-pick what we need in 0.1 that has been recently merged into master.

I don't think that this change, or the sparse/ragged refactor in general, is consistent with release/0.1.  The sparse/ragged refactor was done in master, on top of the huge mapper compaction PR, which isn't present in release/0.1.

> We should just point release/0.1 at master

Not sure what you mean by this - can you clarify?

**Pull request merged**
