### PR TITLE
Simplified some elements of the id_ class.

### PR DESCRIPTION
**Pull request by staleyLANL**
Commented-out code that appears to be unused (and in some cases wrong); will let CI run and pass (I hope) before removing permanently.
Updated utils/test/ files per the above.
Put in comments to help clarify some of the bitwise stuff that's going on.
Entered remarks on some seemingly strange constructions; will look into those more deeply.

### CODE REVIEW

**Comment by ipdemes** [comment]
@staley LANL you need to run format-FLeCSI

**Comment by staleyLANL** [comment]
Is this the same as running:


     make format


in build/ ?


Martin

--
Martin Staley
CCS-7, Applied Computer Science
Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545
Office: 03/508/122
Phone: 1-505-667-7108



________________________________

**Comment by ipdemes** [comment]
@staleyLANL try to do "make formet-FleCSI" in build directory

**Comment by staleyLANL** [comment]
Will do, as soon as my build is finished.

**Comment by ipdemes** [comment]
@charest , @tuxfan : could you, please, look at this?

**Comment by tuxfan** [comment]
> Will do, as soon as my build is finished.

I think that the command is now, "make format-Project". You can do, "make help" to see the available targets.

**Pull request merged**
