### PR TITLE
Fix formatting for recently added ragged/sparse code

### PR DESCRIPTION
**Pull request by cferenba**
I neglected to run clang-format on my previous PR.  Sorry about that.  This PR fixes it - no changes to functionality, just formatting.

### CODE REVIEW

**Comment by ktsai7** [comment]
Ohh I think the `make format-FleCSI` is needed for legion build too

**Comment by cferenba** [comment]
@ktsai7 : you are right, I did not do the legion build.  Will fix momentarily.

**Comment by cferenba** [comment]
@junghans or @ktsai7 : I cannot view the page on gitlab.com that tells why the CI failed.  Is there a group I need to be added to?

**Comment by ktsai7** [comment]
yes, I will add you to the group, what's your gitlab.com username?

**Comment by cferenba** [comment]
My username is "cferenba", same as here.

**Comment by junghans** [comment]
@ktsai7, I think we should just make the repos on gitlab.com world-readable after all they are jsut mirror of the github repos, which are world-readable. @ddd any objections?

**Comment by ktsai7** [comment]
sure, I can make it public after I get an ok from @ddaniel

**Pull request merged**
