### PR TITLE
Improving NB tree

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@nickm319 : please review for @JulienLoiseau

**Comment by nickm319** [comment]
Please use size_t instead of int for induction variables in existing FleCSI files. Otherwise, looks good. Thanks

**Comment by junghans** [comment]
@JulienLoiseau, just add a fix for @nickm319's comment to the same branch and it will show up in this pull request.

**Comment by ipdemes** [comment]
@junghans @JulienLoiseau : what is the status of this pull request? Can we close it?

**Pull request closed without merging**
