### PR TITLE
Changes to the function registration model.

### PR DESCRIPTION
**Pull request by junghans**
Reopen of #240.

### CODE REVIEW

**Comment by junghans** [comment]
@staleyLANL: please fix compile errors first.

**Comment by junghans** [comment]
@jpietarilagraham: It seems the refactor branch itself is broken too: https://travis-ci.org/laristra/flecsi/builds/230454058

**Comment by jpietarilagraham** [comment]
odd...


[jgraham@cn115 build-refactor]$ ctest
Test project /home/jgraham/github/flecsi/build-refactor
      Start  1: dcrs
 1/25 Test  #1: dcrs .............................   Passed    0.29 sec
      Start  2: devel-dcrs
 2/25 Test  #2: devel-dcrs .......................   Passed    0.18 sec
      Start  3: data_client
 3/25 Test  #3: data_client ......................***Exception: SegFault  0.09 sec
      Start  4: compaction
 4/25 Test  #4: compaction .......................   Passed    0.06 sec
      Start  5: legion_dh1
 5/25 Test  #5: legion_dh1 .......................***Failed    0.16 sec
      Start  6: launch
 6/25 Test  #6: launch ...........................   Passed    0.01 sec
      Start  7: processor
 7/25 Test  #7: processor ........................   Passed    0.02 sec
      Start  8: task_hash
 8/25 Test  #8: task_hash ........................   Passed    0.00 sec
      Start  9: simple_function
 9/25 Test  #9: simple_function ..................   Passed    0.20 sec
      Start 10: simple_task
10/25 Test #10: simple_task ......................   Passed    0.23 sec
      Start 11: internal_task
11/25 Test #11: internal_task ....................***Failed    0.27 sec
      Start 12: execution_structure
12/25 Test #12: execution_structure ..............   Passed    1.17 sec
      Start 13: ghost_access
13/25 Test #13: ghost_access .....................   Passed    0.27 sec
      Start 14: point
14/25 Test #14: point ............................   Passed    0.01 sec
      Start 15: space_vector
15/25 Test #15: space_vector .....................   Passed    0.00 sec
      Start 16: simple_definition
16/25 Test #16: simple_definition ................   Passed    0.01 sec
      Start 17: dual
17/25 Test #17: dual .............................   Passed    0.00 sec
      Start 18: structured
18/25 Test #18: structured .......................   Passed    0.00 sec
      Start 19: closure
19/25 Test #19: closure ..........................   Passed    0.01 sec
      Start 20: devel-closure
20/25 Test #20: devel-closure ....................   Passed    0.00 sec
      Start 21: const_string
21/25 Test #21: const_string .....................   Passed    0.00 sec
      Start 22: factory
22/25 Test #22: factory ..........................   Passed    0.01 sec
      Start 23: reorder
23/25 Test #23: reorder ..........................   Passed    0.00 sec
      Start 24: any
24/25 Test #24: any ..............................   Passed    0.00 sec
      Start 25: reflection
25/25 Test #25: reflection .......................   Passed    0.00 sec

88% tests passed, 3 tests failed out of 25

Total Test time (real) =   3.26 sec

The following tests FAILED:
	  3 - data_client (SEGFAULT)
	  5 - legion_dh1 (Failed)
	 11 - internal_task (Failed)
Errors while running CTest
[jgraham@cn115 build-refactor]$ module li
Currently Loaded Modulefiles:
  1) gcc/6.2.0             2) mpich/3.2-gcc_6.2.0   3) cmake/3.7.1
[jgraham@cn115 build-refactor]$ 


--
Jonathan Graham
Applied Computer Science, CCS-7
(505) 665-2482 / jgraham@lanl.gov
________________________________________

**Comment by junghans** [comment]
What are you using for `FLECSI_RUNTIME_MODEL` ? Maybe we should disable all of them, but `legion` for now.

**Comment by jpietarilagraham** [comment]
Yes, that might be a good idea.

--
Jonathan Graham
Applied Computer Science, CCS-7
(505) 665-2482 / jgraham@lanl.gov
________________________________________

**Comment by ollielo** [comment]
@junghans ,

Is Travis actually building the refactor branch? The way I understand it, flecsi was cloned in the Dockerfile in flecsi-third-party and it was built for flecsi/master branch. In the flecsi/Dockerfile, there is nothing to fetch new version for checkout the refactor branch for what we want to test. Did I miss something?

**Comment by junghans** [comment]
@jpietarilagraham: Now i get:
```
In file included from /usr/local/include/realm/profiling.h:29:0,
                 from /usr/local/include/realm/realm.h:23,
                 from /usr/local/include/legion/legion_types.h:42,
                 from /usr/local/include/legion/legion.h:36,
                 from /home/flecsi/flecsi/flecsi/data/test/legion/compaction.cc:8:
/usr/local/include/realm/instance.h:64:7: error: 'LegionRuntime' does not name a type
       LegionRuntime::Accessor::RegionAccessor<LegionRuntime::Accessor::AccessorType::Generic> get_accessor(void) const;
       ^~~~~~~~~~~~~
In file included from /usr/local/include/legion/legion.h:36:0,
                 from /home/flecsi/flecsi/flecsi/data/test/legion/compaction.cc:8:
/usr/local/include/legion/legion_types.h:1416:26: error: 'Accessor' in namespace 'LegionRuntime' does not name a type
   typedef LegionRuntime::Accessor::ByteOffset ByteOffset;
                          ^~~~~~~~
```
it seems you are using a different version of legion than the one in flecsi-third-party (StanfordLegion/legion@541d7b7). Or?

**Comment by jpietarilagraham** [comment]
commit 28718798da82369c54adf0acc6b8260f1d8dbe36
Author: Mike <mebauer@cs.stanford.edu>
Date:   Mon May 1 00:23:41 2017 -0700

    legion: small bug fix for temporary copies

Is this the one in third-party?
--
Jonathan Graham
Applied Computer Science, CCS-7
(505) 665-2482 / jgraham@lanl.gov
________________________________________

**Comment by junghans** [comment]
@ollielo: Yes, in https://travis-ci.org/laristra/flecsi/jobs/230606085#L252 travis does
```
git fetch origin +refs/pull/245/merge
```
which is a merge of this pull request (#245) and the current target branch (`refactor`).
You can get the same code locally by:
```
git fetch origin +refs/pull/245/merge
git checkout FETCH_HEAD
```
Please note that `merge` is different from the `head` of the pull request, which you would get from:
```
git fetch origin +refs/pull/245/head
```

**Comment by junghans** [comment]
Nope, third-party is using StanfordLegion/legion@541d7b7, I will try to bump it to StanfordLegion/legion@ 28718798da82369c54adf0acc6b8260f1d8dbe36.

**Pull request merged**
