### PR TITLE
Add simple test of legion serdez capability

### PR DESCRIPTION
**Pull request by cferenba**
This PR adds a simple test to demonstrate the legion serdez (serialize/deserialize) capability.

Note that this version of the test bypasses flecsi almost completely and uses legion directly.  In order to use this within flecsi, we'd need to add flecsi machinery to register custom serdez operators, similar to how we currently register tasks, reductions, etc.  I'll try this in a future PR.

Also note that the RegionAccessor::write method copies its data using a bitwise copy.  This can cause problems for classes that require a custom copy constructor (such as `std::vector`, which caused this test to fail when I tried using it in place of my custom vector).

### CODE REVIEW

**Comment by ktsai7** [comment]
@cferenba Is this the same as PR #576?

**Comment by cferenba** [comment]
Yes, this is the same as #576.  This is the older one, it uses a fork instead of a branch.

**Comment by ktsai7** [comment]
Would it be safe to say we can close this one and just focus on #576?

**Comment by cferenba** [comment]
Yes, that's fine - this can be closed.  I'll do it now.

**Pull request closed without merging**
