### PR TITLE
Irina hpx

### PR DESCRIPTION
**Pull request by ipdemes**
@hkaiser : for simplicity, I have pushed the adding_hpx branch from your repository to FLeCSI with following changes: I've disabled most of the tests.
Then, in the irina_hpx branch, I have worked on fixing compile-time errors for the HPX runtime.Everything compiles/pass form me there and I expect the branch will pass travis check. 
After you review the changes we can probably merge this into the FLeCSI master branch.

### CODE REVIEW

**Comment by ipdemes** [comment]
@junghans , could you, please, help me disabling clang builds for hpx? What I tried didn't work ..

**Comment by charest** [comment]
The allowed failures didnt work?  I noticed you have to make sure the "env" line has to be exactly the same (spaces an all) as whats in the testing matrix.

**Comment by charest** [comment]
For example, you have
env:
  matrix:
    DISTRO=fedora RUNTIME=hpx    COVERAGE=ON

But, 
matrix:
  allow_failures:
    env: DISTRO=fedora RUNTIME=hpx COVERAGE=ON

Match the spaces between hpx and COVERAGE and I bet it will work as expected

**Comment by ipdemes** [comment]
@charest : Thanks, I have just changed .travis file according to your suggestions.

**Pull request merged**
