### PR TITLE
M3p

### PR DESCRIPTION
**Pull request by ryosukep**

### CODE REVIEW

**Comment by tuxfan** [comment]
@charest will review and we will see if CI passes.

**Comment by ktsai7** [comment]
@charest if you run 'make format', does it work on your local machine?

**Comment by ktsai7** [comment]
@charest is this in master? I checked for the commits in this PR and couldn't find them in master...

**Comment by cferenba** [comment]
These are in master.  They got merged into feature/parallel in 0f67bd2b7, which later got merged into master.

**Comment by ktsai7** [comment]
So we can close this PR then?

**Comment by cferenba** [comment]
Yes, we can.

**Pull request closed without merging**
