### PR TITLE
Updated Boost Linkage to Modern Targets

### PR DESCRIPTION
**Pull request by rspavel**
Updated Boost linkage in CMake to use more modern imported targets
(Documented as part of FindBoost as of CMake 3.5.2. Provided by Boost
install's cmake targets otherwise)

This resolves the issue where CMake may find the desired Boost install
by specifying BOOST_DIR but only provide -lboost_program_options-mt at
the link line. This results in undefined behavior where the system Boost
may take priority and cause linking errors.
By using the more modern imported targets CMake will provide the full
path to the desired library and ensure that the correct version of Boost
is linked to.

### CODE REVIEW

**Comment by junghans** [comment]
@ipdemes didn't you already fix that same issue in refactor, but simply bumping the CMake minimum required version?

**Comment by ipdemes** [comment]
@junghans  yes, I believe that @rspavel change is not necessary and the issue will be fixed if we replace  3.0 with 3.5 here:
https://github.com/laristra/flecsi/blob/master/CMakeLists.txt#L26

**Comment by rspavel** [comment]
@ipdemes and @junghans There are style/design reasons to use modern cmake and targets, but mostly I just wanted to fix this functionality so that I could continue work and simplify building dependencies.

Can we get the fix from refactor migrated to master and other live branches?

**Comment by ipdemes** [comment]
@rspavel : I have just created a new pull request for this:
https://github.com/laristra/flecsi/pull/557

**Comment by ipdemes** [comment]
@rspavel : we need other boost libraries for HPX so we need ${Boost_libraries}

**Comment by rspavel** [comment]
@ipdemes This starts getting in to philosophical territory, but I would still argue we want Boost::FOO as that explicitly indicates which libraries we need and (presumably) gives better error messages if we don't find it

So we "should" talk with the HPX devs to determine specifically which compiled boost libraries they need and explicitly add and propagate those imported targets

Like I said, more philosophical at this point, but it tends to keep things cleaner and makes it more obvious when we are just dependent on a limited enough subset of boost that we may consider dropping it as a required TPL.

**Comment by ipdemes** [comment]
@rspavel we specify what packages we need in cinch:
https://github.com/laristra/cinch/tree/master/cmake#L29-L35

**Comment by rspavel** [comment]
@ipdemes Yes, and the idea would be that only code that needs boost::atomic would link it. It is mostly rendered moot since we aggregate all our libraries in CINCH_RUNTIME_LIBRARIES anyway which is why it is more of a philosophical territory. But in general (imported) targets give benefits regarding how include directories and link lines are propagated as well as future proofing for TPLs like HDF5 or MPI that don't have as clean of a set of includes and libraries

Like I said, I don't care too much how we fixed it. I think the correct way would be explicit targets and bumping up the cmake version, but i only need one to make progress.

**Pull request closed without merging**
