### PR TITLE
Fix/staley/hash function

### PR DESCRIPTION
**Pull request by staleyLANL**
New string_hash() function to solve Issue #455.

### CODE REVIEW

**Comment by jpietarilagraham** [comment]
This does not seem to fix the reproducer that I have:

https://gitlab.lanl.gov/jgraham/CANGA/tree/reproducer

Remember to clone --recursive

The build is rather tricky.  On darwin, I'm using module load deprecated mpich/3.2.1-gcc_8.1.0; module load cmake/3.11.1; module load boost/1.67.0_gcc-8.1; export CMAKE_PREFIX_PATH=~/opt/flecsi-mpi; export BOOST_ROOT=~/opt/boost-1.64.0

After you have 3rd party built, read:

https://gitlab.lanl.gov/jgraham/CANGA/blob/reproducer/FleCSI/README.md

If you run into trouble, just come knock on my door.

**Comment by jlippuner** [comment]
I think the AST stuff should be removed from this PR

**Comment by staleyLANL** [comment]
Yes, I noticed that too, after I'd put in the pull request.


--
Martin Staley
CCS-7, Applied Computer Science
Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545
Office: 03/508/122
Phone: 1-505-667-7108



________________________________

**Comment by jpietarilagraham** [comment]
Oops, github lists commits in the opposite order to git log and gitk.  I checked out the first commit instead of the last one.  And then I had problems with someone renaming __flecsi_internal_register_legion_task to flecsi_internal_register_legion_task.  My issue is resolved.

**Comment by jlippuner** [comment]
@jpietarilagraham I can confirm that Martin's new hash functions gets rid of the following collisions.

PREVIOUSLY:
```
COLLISION: 'Sx_a_anidf' collides with 'Sl_a_anidr'
COLLISION: 'Sx_a_anidr' collides with 'Sl_a_anidf'
COLLISION: 'Sx_a_avsdf' collides with 'Sl_a_avsdr'
COLLISION: 'Sx_a_avsdr' collides with 'Sl_a_avsdf'
```

NOW these collisions are gone.

I couldn't get CANGA to work, but I extracted all the names of the registered fields (I just grepped for REGISTER_*_FIELD) and I put them into the FleCSI hash test (`flecsi/utils/test/hash.cc`). There are no collisions in that list of fields. So if this is still not working with CANGA then it's either not due to a hash collision or there are some field names that you use that I missed. If you still get hash collisions, could you please give us the strings that collide?

**Comment by jlippuner** [comment]
> Oops, github lists commits in the opposite order to git log and gitk. I checked out the first commit instead of the last one. And then I had problems with someone renaming __flecsi_internal_register_legion_task to flecsi_internal_register_legion_task. My issue is resolved.

Great!

**Comment by staleyLANL** [comment]
Will do. It turns out that Jonathan's issue was due, as he said, to not actually using the new code. 😊


--
Martin Staley
CCS-7, Applied Computer Science
Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545
Office: 03/508/122
Phone: 1-505-667-7108



________________________________

**Comment by jlippuner** [comment]
Please also remove the merge commits from the PR. This PR should only be the last two commits. Your "New string_hash() function to solve Issue #455." and my modification to the hash test (assuming you approve)

**Comment by jlippuner** [comment]
Oh and in case anybody's interested: Using Martin's new hash function has no measurable impact on compile time

**Comment by staleyLANL** [comment]
The additional code in the hash test looks great, Jonas. Thanks!


--
Martin Staley
CCS-7, Applied Computer Science
Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545
Office: 03/508/122
Phone: 1-505-667-7108



________________________________

**Comment by jlippuner** [comment]
Thanks Martin! Do you think you could squash this PR into a single commit to keep the history clean (instead of adding and removing a bunch of other stuff)? Just force-push the squashed commit.

**Pull request merged**
