### PR TITLE
increased minimum required version for cmake to 3.5

### PR DESCRIPTION
**Pull request by ipdemes**
Fix #555

### CODE REVIEW

**Comment by junghans** [comment]
Why?

**Comment by ipdemes** [comment]
@junghans : I should probably do 3.3 instead. The issue when Cmake is linking with -llib_name instead of the /full/path/to/the/library was fixed in 3.3

**Comment by ktsai7** [comment]
@ipdemes @junghans @rspavel So do we want #555 or #557? Probably don't need 2 PRs on this...

**Comment by rspavel** [comment]
@ktsai7 As mentioned in #555, I think the "correct" solution is both. But most of the benefits of imported targets go away when you aggregate link lines.

Mostly I just want/need something that makes master and related branches buildable without heavy PATH editing and from a progress perspective I don't care which one.

**Pull request merged**
