### PR TITLE
added missing include

### PR DESCRIPTION
**Pull request by charest**

### CODE REVIEW

**Comment by nray** [comment]
@charest This issue was fixed in a previous PR.

**Comment by cferenba** [comment]
@nray is right : this is fixed on master.  Though it looks like @charest was working off a checkout that isn't current.

**Comment by cmsquared** [comment]
oooh is this what is breaking the PRs in flecsi-sp?  Did you mean to merge this into release/0.1?

**Comment by charest** [comment]
Okay i guess it is not needed.  But yes this is the issue that was breaking the flecsi-sp CI.

**Comment by cmsquared** [comment]
The FlecSI-SP CI that was broken is on the release/0.1 branch.  So the missing header include should be added to that branch of FleCSI.  FleCSI-sp/release/0.1 also needs to build against FleCSI/release/0.1, so with @ktsai7 's help, we're getting a docker container set up with that FleCSI branch built.

**Pull request closed without merging**
